dist: xenial
language: python
python: "3.6"
git:
  depth: 1 # clone only latest revision of repository
cache:
  - pip
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv graph
script:
  - goodtables metadata/datapackage.json # structure and schema validation
  - python lib_py/validation/relations.py datasets # relation validation