name: Check-Relations

on:	
    push:

jobs:	
    run-tests:	
        runs-on: ubuntu-latest	
        allow_failure: true

        steps:	
            - uses: actions/checkout@v2	
            - name: Install
              run: |
                sudo apt install python3.8
                python3.8 -m pip install setuptools
                python3.8 -m pip install git+https://github.com/ddionrails/paneldata_pipeline@master#egg=paneldata_pipeline
            - name: Test Relations
              run: |
                python3.8 -m paneldata_pipeline.check_relations -i ddionrails/ -r ddionrails/relations.json
